//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lab1Kokoro
{
    using System;
    using System.Collections.Generic;
    
    public partial class CLIENTS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CLIENTS()
        {
            this.TABLEBOOKING = new HashSet<TABLEBOOKING>();
        }
    
        public int ID_CLIENTS { get; set; }
        public string FIRSTNAME { get; set; }
        public string SURNAME { get; set; }
        public string MIDNAME { get; set; }
        public Nullable<int> NUMBER { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TABLEBOOKING> TABLEBOOKING { get; set; }
    }
}
