//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lab1Kokoro
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class NIGHTCLUBEntities3 : DbContext
    {
        public NIGHTCLUBEntities3()
            : base("name=NIGHTCLUBEntities3")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CLIENTS> CLIENTS { get; set; }
        public virtual DbSet<EVENTS_CLIENTS> EVENTS_CLIENTS { get; set; }
        public virtual DbSet<TABLEBOOKING> TABLEBOOKING { get; set; }
    }
}
