//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lab1Kokoro
{
    using System;
    using System.Collections.Generic;
    
    public partial class TABLEBOOKING
    {
        public int ID_TABLEBOOKING { get; set; }
        public Nullable<int> CLIENT_ID { get; set; }
        public Nullable<int> EVENT_ID { get; set; }
        public Nullable<int> TABLE_NUMBER { get; set; }
        public Nullable<System.DateTime> BOOKING_DATE { get; set; }
    
        public virtual CLIENTS CLIENTS { get; set; }
        public virtual EVENTS_CLIENTS EVENTS_CLIENTS { get; set; }
    }
}
